export const erros = {
  P1000: { message: "Erro na conexão com o banco de dados. Verifique as credenciais de acesso."},
  P1001: { message: "Erro ao acessar banco de dados. Verifique se a conexão está ativa."},
  P1002: { message: "Tempo de requisição expirado. Tente novamente."},
  P1003: { message: "O banco de dados não existe."},
  P1008: { message: "Tempo de requisição expirado. Tente novamente."},
  P1009: { message: "Banco de dados já existe!"},
  P1010: { message: "O usuário teve acesso negado ao banco de dados"},
  P1011: { message: "Erro ao abrir uma conexão TLS."},
  P1012: { message: "Argumento/Atributo inválido."},
  P1013: { message: "A string do banco de dados fornecida é inválida."},
  P1014: { message: "Variável não compátivel com o do banco de dados."},
  P1015: { message: "Seu esquema Prisma está usando recursos que não são suportados pela versão do banco de dados. Verifique a versão do Prisma."},
  P1016: { message: "Sua consulta tinha um número incorreto de parâmetros. Favor verificar a request."},
  P1017: { message: "O servidor fechou a conexão."},
  P2000: { message: "O valor fornecido para a coluna é muito longo para o tipo da coluna."},
  P2001: { message: "O registro procurado na condição WHERE não existe."},
  P2002: { message: "Valor já existente no banco de dados, definido como chave primária."},
  P2003: { message: "Valor já existente no banco de dados, definido como chave estrangeira."},
  P2004: { message: "Falha ao fazer cadastro no banco de dados."},
  P2005: { message: "O valor armazenado no banco de dados para o campo solicitado é inválido para o tipo do campo."},
  P2006: { message: "O valor fornecido para o campo não é válido."},
  P2007: { message: "Erro de validação de dados."},
  P2008: { message: "Falha ao analisar a consulta."},
  P2009: { message: "Falha ao validar a consulta"},
  P2010: { message: "Falha na consulta bruta."},
  P2011: { message: "Foi feito um cadastro nula."},
  P2012: { message: "Faltando um valor obrigatório."},
  P2013: { message: "Faltando o argumento obrigatório para o campo."},
  P2014: { message: "A mudança que você está tentando fazer violaria o tipo da variável, definido como chave estrangeira."},
  P2015: { message: "Não foi possível encontrar um registro relacionado."},
  P2016: { message: "Erro de interpretação da consulta."},
  P2017: { message: "Os registros de relação entre as variáveis não estão conectados."},
  P2018: { message: "Os registros conectados necessários não foram encontrados."},
  P2019: { message: "Erro de entrada."},
  P2020: { message: "Valor fora do intervalo para o tipo."},
  P2021: { message: "A tabela não existe no banco de dados atual."},
  P2022: { message: "A coluna não existe no banco de dados atual."},
  P2023: { message: "Dados de coluna inconsistentes."},
  P2024: { message: "Tempo limite de busca de uma nova conexão do pool de conexões."},
  P2025: { message: "Uma operação falhou porque depende de um ou mais registros que foram necessários, mas não foram encontrados."},
  P2026: { message: "O provedor de banco de dados atual não oferece suporte a um recurso usado por essa consulta"},
  P2027: { message: "Ocorreram vários erros no banco de dados durante a execução da consulta."},
  P2028: { message: "Erro na API de transação."},
  P2029: { message: "Erro de limite de parâmetro de consulta excedido."},
  P2030: { message: "Não é possível encontrar um índice de texto completo para usar na pesquisa. Verifique o seu esquema Prisma."},
  P2031: { message: "O Prisma precisa realizar transações, o que exige que seu servidor MongoDB seja executado como um conjunto de réplicas."},
  P2033: { message: "Um número usado na consulta não cabe em um número inteiro assinado de 64 bits. Considere usar BigIntcomo tipo de campo se estiver tentando armazenar números inteiros grandes."},
  P2034: { message: "A transação falhou devido a um conflito de gravação ou impasse. Tente novamente a transação."},
  P2035: { message: "Violação de declaração no banco de dados."},
  P2036: { message: "Erro no conector externo."},
  P2037: { message: "Muitas conexões de banco de dados abertas."},
  P3000: { message: "Falha ao criar banco de dados."},
  P3001: { message: "Migração possível com alterações destrutivas e possível perda de dados."},
  P3002: { message: "A tentativa de migração foi revertida"},
  P3003: { message: "O formato das migrações mudou, as migrações salvas não são mais válidas. Para resolver este problema, siga os passos em: https://pris.ly/d/migrate"},
  P3004: { message: "O banco de dados é um banco de dados do sistema, não deve ser alterado com a migração prisma. Conecte-se a outro banco de dados."},
  P3005: { message: "O esquema do banco de dados não está vazio. Leia mais sobre como definir a linha de base de um banco de dados de produção existente: https://pris.ly/d/migrate-baseline"},
  P3006: { message: "A migração não foi aplicada corretamente ao banco de dados shadow."},
  P3007: { message: "Alguns dos recursos de visualização solicitados ainda não são permitidos no mecanismo de esquema. Remova-os do seu modelo de dados antes de usar migrações."},
  P3008: { message: "A migração já está registrada como aplicada no banco de dados."},
  P3009: { message: "Migração encontrou migrações com falha no banco de dados de destino, novas migrações não serão aplicadas. Leia mais sobre como resolver problemas de migração em um banco de dados de produção: https://pris.ly/d/migrate-resolve"},
  P3010: { message: "O nome da migração é muito longo. Não deve ter mais de 200 caracteres (bytes)."},
  P3011: { message: "A migração não pode ser revertida porque nunca foi aplicada ao banco de dados."},
  P3012: { message: "A migração não pode ser revertida porque não está num estado de falha."},
  P3013: { message: "Matrizes de provedores de fonte de dados não são mais suportadas na migração. Altere sua fonte de dados para usar um único provedor. Leia mais em https://pris.ly/multi-provider-deprecation"},
  P3014: { message: "O Prisma Migrate não conseguiu criar o banco de dados shadow. Certifique-se de que o usuário do banco de dados tenha permissão para criar bancos de dados. Leia mais sobre o banco de dados shadow (e soluções alternativas) em https://pris.ly/d/migrate-shadow."},
  P3015: { message: "Não foi possível encontrar o arquivo de migração. Exclua o diretório ou restaure o arquivo de migração."},
  P3016: { message: "O método substituto para redefinições do banco de dados falhou, o que significa que o Migrate não conseguiu limpar o banco de dados completamente."},
  P3017: { message: "A migração não foi encontrada. Certifique-se de que a migração existe e de que você incluiu o nome completo do diretório."},
  P3018: { message: "Falha ao aplicar uma migração. Novas migrações não podem ser aplicadas antes que o erro seja recuperado. Leia mais sobre como resolver problemas de migração em um banco de dados de produção: https://pris.ly/d/migrate-resolve"},
  P3019: { message: "O provedor de fonte de dados {provider}especificado em seu esquema não corresponde ao especificado em migração_lock.toml. Remova seu diretório de migração atual e inicie um novo histórico de migração com prisma Migrate dev. Leia mais: https://pris.ly/d /migrar-provider-switch."},
  P3020: { message: "A criação automática de bancos de dados shadow está desabilitada no Azure SQL. Configure um banco de dados shadow usando o shadowDatabaseUrlatributo datasource. Leia a página de documentos para mais detalhes: https://pris.ly/d/migrate-shadow"},
  P3021: { message: "Chaves estrangeiras não podem ser criadas neste banco de dados. Saiba mais como lidar com isso: https://pris.ly/d/migrate-no-foreign-keys."},
  P3022: { message: "A execução direta de instruções SQL DDL (linguagem de definição de dados) está desabilitada neste banco de dados. Leia mais aqui sobre como lidar com isso: https://pris.ly/d/migrate-no-direct-ddl"},
  P4000: { message: "A operação de introspecção falhou ao produzir um arquivo de esquema."},
  P4001: { message: "O banco de dados introspectado estava vazio."},
  P4002: { message: "O esquema do banco de dados introspectado era inconsistente."}
}